"""Timing configuration for panel cleaning and plant watering."""

MAIN_VALVE_MOVEMENT_SECONDS = 30
PANEL_SPRINKLER_SECONDS = 60
PLANT_WATERING_SECONDS = 5
WAIT_AFTER_PUMP_STOP_SECONDS = 10
WATER_SETTLING_SECONDS = 3