[project]
name = "home-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vishal Daga", email = "vishal.daga@kearney.com" }
]
requires-python = ">=3.13"
dependencies = [
    "b2sdk>=2,<3",
    "fastapi>=0.141.1",
    "gpiozero>=2.0.1.post3",
    "lgpio>=0.2.2.0 ; platform_machine == 'aarch64' and sys_platform == 'linux'",
    "pygobject>=3.56.3 ; sys_platform == 'linux'",
    "uvicorn>=0.52.1",
]

[project.scripts]
home-automation = "home_automation:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
