import {
  Camera,
  Droplets,
  Gauge,
  Leaf,
  Router,
  Waves,
} from "lucide-react";

export const RELAYS = [
  {
    key: "ro_power",
    name: "RO Purifier",
    channel: "IN1",
    gpio: 2,
    icon: Droplets,
    description: "Reverse osmosis water purifier power.",
    wiringNote: "Relay OFF supplies power through the normally closed contact.",
  },
  {
    key: "router_power",
    name: "Main Router",
    channel: "IN2",
    gpio: 3,
    icon: Router,
    description: "Terrace optical network unit and main router power.",
    wiringNote: "Relay OFF supplies power through the normally closed contact.",
  },
  {
    key: "camera_power",
    name: "Camera Power Line",
    channel: "IN3",
    gpio: 12,
    icon: Camera,
    description: "Shared power line for the ESP32 cameras.",
    wiringNote: "Relay ON supplies power through the normally open contact.",
  },
  {
    key: "plant_valve",
    name: "Plant Solenoid Valve",
    channel: "IN4",
    gpio: 13,
    icon: Leaf,
    description: "Controls water flow to the plant-watering pipeline.",
    wiringNote: "Relay ON opens the normally closed solenoid valve.",
  },
  {
    key: "main_valve",
    name: "Main Motorised Valve",
    channel: "IN5",
    gpio: 26,
    icon: Waves,
    description: "Controls the main water path for sprinklers and plants.",
    wiringNote: "Relay ON selects opening; relay OFF selects closing.",
  },
  {
    key: "pump",
    name: "Water Pump",
    channel: "IN6",
    gpio: 21,
    icon: Gauge,
    description: "Controls the overhead-tank pump circuit.",
    wiringNote: "Relay ON activates the pump control circuit.",
  },
];